# Global
output_dir: './results'
training_enabled: 0
wandb_enabled: 0

# Training
seed: 42
learning_rate: 0.0001
epochs: 50
batch_size: 64             # Test with 32
weight_decay: 0.1
val_interval: 20           ## Validation every 100 iterations

# CLIP model
projection_dim: 1024
image_encoder: 'resnet50'
image_embedding: 2048
text_encoder: "distilbert-base-uncased"
text_embedding: 768