# Global
folder_path: '/mnt/data/iai/datasets/xray/mimic-cxr-2.0.0.physionet.org/files/'
training_enabled: False
wandb_enabled: False
output_dir: './results'

# Training
seed: 42
epochs: 50
dropout: 0.1
batch_size: 32
eval_interval: 100
learning_rate: 0.0001

# CLIP model
pretrained: True  # for both image encoder and text encoder
trainable: True   # for both image encoder and text encoder

projection_dim: 256
image_encoder: 'resnet50'
image_embedding: 2048
text_encoder: "distilbert-base-uncased"
text_embedding: 768
text_encoder_max_length: 200